const skills = ["React", "TypeScript", "JavaScript", "CSS", "REST APIs", "Git", "Figma", "Agile"];
const expected = ["React", "TypeScript", "Next.js", "GraphQL", "Mentoring", "Testing", "CI/CD", "Accessibility", "Performance"];
const $ = (id) => document.getElementById(id);
let supabaseClient, activeUser, lastAnalysis, authMode = "signin", profilePrompted = false, toastTimer, savedPlans = [], activePlanId = null, completedWeeks = [false, false, false, false], evidenceByWeek = [], taskStepsByWeek = {}, reopenedWeeks = [], activeTaskIndex = null;
function accountName(user = activeUser) { return user?.user_metadata?.full_name?.trim() || ""; }
function initials(name) { return name.split(/\s+/).filter(Boolean).slice(0, 2).map(part => part[0]).join("").toUpperCase(); }
function notify(message, error = false) { const toast = $("toast"); toast.textContent = message; toast.classList.toggle("error", error); toast.classList.add("show"); clearTimeout(toastTimer); toastTimer = setTimeout(() => toast.classList.remove("show"), 3600); }
function updateAccountUi() { const name = accountName(); document.body.classList.toggle("signed-in", Boolean(activeUser)); $("auth-button").textContent = activeUser ? "Sign out" : "Sign in"; $("profile-avatar").textContent = name ? initials(name) : (activeUser ? "PW" : "↗"); }
function setStatus(id, message = "", state = "") { const element = $(id); element.textContent = message; if (state) element.dataset.state = state; else delete element.dataset.state; }
function clearAuthForm() { $("auth-form").reset(); setStatus("auth-status"); }
function openAuth(mode = "signin") { authMode = mode; const signup = mode === "signup"; $("name-fields").hidden = !signup; $("auth-first-name").required = signup; $("auth-last-name").required = signup; $("auth-password").autocomplete = signup ? "new-password" : "current-password"; $("auth-title").innerHTML = signup ? "Create your<br />path." : "Welcome back."; $("auth-copy").textContent = signup ? "Start with a personal space for your career plans, progress, and practice." : "Sign in to pick up your career plan, roadmap progress, and interview practice."; $("auth-submit").innerHTML = signup ? "Create account <span>→</span>" : "Sign in <span>→</span>"; $("auth-mode-toggle").textContent = signup ? "Already have an account? Sign in" : "Create a new account"; setStatus("auth-status"); if (!$("auth-dialog").open) $("auth-dialog").showModal(); }
function openProfile() { const [first = "", ...rest] = accountName().split(" "); $("profile-first-name").value = first; $("profile-last-name").value = rest.join(" "); setStatus("profile-status"); if (!$("profile-dialog").open) $("profile-dialog").showModal(); }
function maybePromptProfile() { if (activeUser && !accountName() && !profilePrompted) { profilePrompted = true; setTimeout(openProfile, 250); } }
async function initAuth() { try { const c = await fetch("/api/config").then(r => r.json()); if (!c.supabaseUrl || !c.supabaseKey) return; supabaseClient = window.supabase.createClient(c.supabaseUrl, c.supabaseKey); activeUser = (await supabaseClient.auth.getSession()).data.session?.user || null; updateAccountUi(); maybePromptProfile(); supabaseClient.auth.onAuthStateChange((_e, s) => { activeUser = s?.user; updateAccountUi(); maybePromptProfile(); }); } catch {} }
const setTheme = theme => { document.body.classList.toggle("light-theme", theme === "light"); $("theme-toggle").textContent = theme === "light" ? "☾ Dark" : "☀ Light"; localStorage.setItem("pathwise-theme", theme); };
setTheme(localStorage.getItem("pathwise-theme") || "dark");
$("theme-toggle").addEventListener("click", () => setTheme(document.body.classList.contains("light-theme") ? "dark" : "light"));
let demoMode = false, analysisBeforeDemo, demoInputsBefore;
const demoInputs = {
  resume: "Frontend engineer with 5 years of experience building responsive customer-facing web applications. Strong in React, TypeScript, JavaScript, REST APIs, accessibility, testing, Git, and Agile delivery. Shipped analytics dashboards and collaborated with designers and product managers.",
  job: "Senior Frontend Engineer — Build accessible, high-performance web experiences using React, TypeScript, Next.js, GraphQL, testing, CI/CD, and strong product collaboration."
};
const demoAnalysis = { score: 78, label: "Strong foundation", edgeTitle: "Your product delivery experience stands out.", edgeCopy: "Your React, TypeScript, and dashboard work gives you credible evidence of shipping customer-facing products.", gapTitle: "Build confidence in Next.js and GraphQL.", gapCopy: "A small portfolio project and two specific interview stories can close these visible gaps.", matched: ["React", "TypeScript", "Product delivery", "Analytics"], strengths: [{ name: "React", resourceUrl: "https://react.dev/learn" }, { name: "TypeScript", resourceUrl: "https://www.typescriptlang.org/docs/handbook/intro.html" }, { name: "JavaScript", resourceUrl: "https://javascript.info/first-steps" }, { name: "CSS", resourceUrl: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics" }, { name: "REST APIs", resourceUrl: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Client-side_APIs/Introduction" }, { name: "Git", resourceUrl: "https://docs.github.com/en/get-started/start-your-journey/hello-world" }, { name: "Figma", resourceUrl: "https://help.figma.com/hc/en-us/categories/360002042553-Get-started" }], gaps: ["Next.js", "GraphQL", "Mentoring"], roadmap: [["WEEK 01", "Sharpen your résumé", "Rewrite three experience bullets around measurable customer impact."], ["WEEK 02", "Build one focused feature", "Create a small Next.js project and document your technical decisions."], ["WEEK 03", "Practice your leadership story", "Prepare two STAR examples about influence and difficult trade-offs."], ["WEEK 04", "Apply with intention", "Tailor five applications and lead with your strongest product evidence."]].map(([week, title, detail]) => ({ week, title, detail })) };
async function extractResumeText(file) { const extension = file.name.split(".").pop()?.toLowerCase(); if (extension === "pdf") { if (!window.pdfjsLib) throw new Error("PDF reader is still loading. Try again in a moment."); const pdf = await window.pdfjsLib.getDocument({ data: new Uint8Array(await file.arrayBuffer()) }).promise; const pages = []; for (let pageNumber = 1; pageNumber <= pdf.numPages; pageNumber += 1) { const page = await pdf.getPage(pageNumber); const content = await page.getTextContent(); pages.push(content.items.map(item => item.str).join(" ")); } return pages.join("\n\n"); } if (extension === "docx") { if (!window.mammoth) throw new Error("Word reader is still loading. Try again in a moment."); return (await window.mammoth.extractRawText({ arrayBuffer: await file.arrayBuffer() })).value; } if (["txt", "md"].includes(extension || "")) return file.text(); throw new Error("Please choose a PDF, DOCX, TXT, or MD file."); }
$("resume-file").addEventListener("change", async event => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 5 * 1024 * 1024) { $("file-status").textContent = "Please choose a file smaller than 5 MB."; return; } try { $("file-status").textContent = `Reading ${file.name}…`; const text = (await extractResumeText(file)).trim(); if (!text) throw new Error("No selectable text was found. For a scanned PDF, paste the text instead."); $("resume").value = text; $("file-status").textContent = `Loaded ${file.name}`; } catch (error) { $("file-status").textContent = error.message || "Could not read that file. Paste the text instead."; } });

function words(text) { return text.toLowerCase().replace(/[^a-z0-9+#./ ]/g, " "); }
function matchSkills(resume, job) {
  const resumeWords = words(resume); const jobWords = words(job);
  const found = expected.filter(skill => resumeWords.includes(words(skill)) || (jobWords.includes(words(skill)) && resumeWords.includes(words(skill))));
  const gaps = expected.filter(skill => jobWords.includes(words(skill)) && !resumeWords.includes(words(skill)));
  return { found: found.length ? found : skills.slice(0, 4), gaps: gaps.length ? gaps.slice(0, 4) : ["Leadership", "System design", "Impact stories"] };
}
function atsReadiness(resume, job) { const resumeWords = words(resume); const roleKeywords = expected.filter(skill => words(job).includes(words(skill))); const matched = roleKeywords.filter(skill => resumeWords.includes(words(skill))); const score = roleKeywords.length ? Math.round((matched.length / roleKeywords.length) * 100) : 60; return { score, matched: matched.length, total: roleKeywords.length }; }
function chips(id, items) { $(id).innerHTML = items.map(item => `<span>${item}</span>`).join(""); }
function safeResourceUrl(value) { try { const url = new URL(value); return url.protocol === "https:" ? url.href : null; } catch { return null; } }
function renderStrengthLinks(strengths) {
  const usable = (strengths || []).map(item => ({ name: String(item?.name || "").trim(), url: safeResourceUrl(item?.resourceUrl) })).filter(item => item.name && item.url).slice(0, 7);
  $("strength-links").innerHTML = usable.map(item => `<a class="strength-link" href="${escapeHtml(item.url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(item.name)}</a>`).join("");
}
function showResults(data) {
  $("results").classList.remove("empty");
  lastAnalysis = data || lastAnalysis;
  const resume = $("resume").value; const job = $("job").value; const { found, gaps } = matchSkills(resume, job); const ats = atsReadiness(resume, job);
  const score = data?.score ?? Math.min(92, Math.max(46, 58 + found.length * 5 - gaps.length * 2));
  $("score").textContent = score; $("meter-fill").style.width = `${score}%`;
  $("score-label").textContent = data?.label || (score > 75 ? "Excellent momentum" : score > 60 ? "Strong foundation" : "Promising direction");
  $("edge-title").textContent = data?.edgeTitle || `Your ${found.slice(0, 2).join(" + ")} experience stands out.`;
  $("edge-copy").textContent = data?.edgeCopy || "These are the strongest proof points to lead with in your résumé and recruiter conversations.";
  $("gap-title").textContent = data?.gapTitle || (gaps.length ? `Build confidence in ${gaps.slice(0, 2).join(" and ")}.` : "Polish your senior-level story.");
  $("gap-copy").textContent = data?.gapCopy || "Focus your next applications and practice around the skills this role makes most visible.";
  $("ats-score").textContent = `${ats.score}%`;
  $("ats-copy").textContent = ats.total ? `${ats.matched} of ${ats.total} role keywords appear in your résumé.` : "Baseline estimate only. Paste a specific job description for an accurate ATS keyword match.";
  const strengths = data?.matched || found; chips("matched", strengths); renderStrengthLinks(data?.strengths); chips("gaps", data?.gaps || gaps); if (data?.roadmap) { plans.splice(0, plans.length, ...data.roadmap.slice(0, 4).map((x, index) => [`WEEK ${String(index + 1).padStart(2, "0")}`, x.title, x.detail])); completedWeeks = plans.map(() => false); evidenceByWeek = plans.map(() => ""); taskStepsByWeek = {}; reopenedWeeks = plans.map(() => false); renderRoadmap(); } $("results").scrollIntoView({ behavior: "smooth", block: "center" });
}
$("analysis-form").addEventListener("submit", async e => { e.preventDefault(); const resume = $("resume").value.trim(); const job = $("job").value.trim(); if (!resume) return notify("Add your résumé or experience before analyzing.", true); if (!job) return notify("Add a target role or job description before analyzing.", true); const button = e.currentTarget.querySelector("button"); button.disabled = true; button.textContent = "Analyzing…"; try { const response = await fetch("/api/analyze", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ resume, job }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); activePlanId = null; completedWeeks = plans.map(() => false); evidenceByWeek = plans.map(() => ""); taskStepsByWeek = {}; reopenedWeeks = plans.map(() => false); $("save-plan").textContent = "Save this plan"; showResults(data); } catch (error) { notify(`Could not analyze yet: ${error.message || "Please try again."}`, true); } finally { button.disabled = false; button.innerHTML = "Reveal my path <span>→</span>"; } });
function exitDemoMode() { if (!demoMode) return; demoMode = false; $("resume").value = demoInputsBefore?.resume || ""; $("job").value = demoInputsBefore?.job || ""; $("file-status").textContent = demoInputsBefore?.fileStatus || "Or upload a PDF, DOCX, TXT, or MD Resume"; if (analysisBeforeDemo) showResults(analysisBeforeDemo); else { lastAnalysis = undefined; $("results").classList.add("empty"); } analysisBeforeDemo = undefined; demoInputsBefore = undefined; $("demo-mode").textContent = "Try guided demo →"; $("demo-exit").hidden = true; }
$("demo-mode").addEventListener("click", () => { if (demoMode) return exitDemoMode(); demoMode = true; analysisBeforeDemo = lastAnalysis; demoInputsBefore = { resume: $("resume").value, job: $("job").value, fileStatus: $("file-status").textContent }; $("resume").value = demoInputs.resume; $("job").value = demoInputs.job; $("file-status").textContent = "Demo experience loaded — no API credits used."; showResults(demoAnalysis); $("demo-mode").textContent = "Exit demo mode"; $("demo-exit").hidden = false; });
$("demo-exit").addEventListener("click", exitDemoMode);
$("auth-button").addEventListener("click", async () => { if (!activeUser) return openAuth(); activeUser = null; updateAccountUi(); clearAuthForm(); $("profile-dialog").close(); const r = await supabaseClient.auth.signOut(); if (r.error) return notify(r.error.message, true); profilePrompted = false; openAuth(); });
$("guest-start").addEventListener("click", () => openAuth("signup"));
$("profile-avatar").addEventListener("click", () => activeUser ? openProfile() : openAuth());
$("close-auth").addEventListener("click", () => $("auth-dialog").close());
$("auth-mode-toggle").addEventListener("click", () => openAuth(authMode === "signin" ? "signup" : "signin"));
$("auth-form").addEventListener("submit", async e => { e.preventDefault(); if (!supabaseClient) return setStatus("auth-status", "Supabase is not connected. Restart the server and check your .env values.", "error"); const email = $("auth-email").value; const password = $("auth-password").value; const r = authMode === "signup" ? await supabaseClient.auth.signUp({ email, password, options: { data: { first_name: $("auth-first-name").value.trim(), last_name: $("auth-last-name").value.trim(), full_name: `${$("auth-first-name").value.trim()} ${$("auth-last-name").value.trim()}`.trim() } } }) : await supabaseClient.auth.signInWithPassword({ email, password }); setStatus("auth-status", r.error?.message || (authMode === "signup" ? "Account created. Check your inbox if confirmation is enabled." : "Signed in."), r.error ? "error" : "success"); if (!r.error && (authMode === "signin" || r.data.session)) $("auth-dialog").close(); });
$("close-profile").addEventListener("click", () => $("profile-dialog").close());
$("profile-form").addEventListener("submit", async e => { e.preventDefault(); const firstName = $("profile-first-name").value.trim(); const lastName = $("profile-last-name").value.trim(); const r = await supabaseClient.auth.updateUser({ data: { first_name: firstName, last_name: lastName, full_name: `${firstName} ${lastName}`.trim() } }); setStatus("profile-status", r.error?.message || "Saved.", r.error ? "error" : "success"); if (!r.error) { activeUser = r.data.user; updateAccountUi(); setTimeout(() => $("profile-dialog").close(), 350); } });
document.querySelectorAll(".tab").forEach(tab => tab.addEventListener("click", () => { document.querySelectorAll(".tab").forEach(x => x.classList.remove("active")); tab.classList.add("active"); document.querySelectorAll(".panel").forEach(x => x.classList.remove("active")); $(tab.dataset.panel).classList.add("active"); if (tab.dataset.panel === "saved") loadSavedPlans(); $(tab.dataset.panel).scrollIntoView({ behavior: "smooth", block: "start" }); }));

const plans = [
  ["WEEK 01", "Name your evidence", "Rewrite three résumé bullets with an action, metric, and outcome."],
  ["WEEK 02", "Close one technical gap", "Build a small Next.js or GraphQL feature and document your choices."],
  ["WEEK 03", "Practice your leadership story", "Prepare two STAR examples about influence, trade-offs, or mentorship."],
  ["WEEK 04", "Ship your signal", "Polish your portfolio and apply to five roles with a tailored opening."],
];
const weekSteps = [
  ["Choose three résumé bullets that best match the target role.", "Rewrite each using: action + tool/skill + measurable outcome.", "Read them aloud and remove vague words such as ‘helped’ or ‘worked on’."],
  ["Pick one missing technical skill from the analysis.", "Build a small focused feature that demonstrates it.", "Add a short README explaining your choices and trade-offs."],
  ["Choose two work stories that show influence or problem-solving.", "Write each as Situation, Task, Action, and Result.", "Practice each answer aloud in under two minutes."],
  ["Choose five roles that genuinely match your evidence.", "Tailor the opening résumé bullets for each role.", "Track every application and one follow-up action."],
];
function taskKey(index) { return `${plans[index]?.[0] || "WEEK"}:${plans[index]?.[1] || index}`; }
function normalizeTaskSteps(value) { if (!Array.isArray(value)) return value || {}; return Object.fromEntries(plans.map((_, index) => [taskKey(index), value[index] || []])); }
async function persistProgress() { if (!activePlanId || !supabaseClient) return; const r = await supabaseClient.from("career_plans").update({ progress: { completedWeeks, evidenceByWeek, taskStepsByWeek, reopenedWeeks } }).eq("id", activePlanId); if (r.error) notify(`Could not save progress: ${r.error.message}`, true); }
function guidanceForWeek(index) {
  const context = `${$("job").value} ${plans[index]?.[1] || ""} ${plans[index]?.[2] || ""}`;
  const isAiMl = /\b(ai|ml|machine learning|applied ml|data science)\b/i.test(context);
  const aiMlSteps = [
    ["Choose one practical Python course or tutorial and complete the first lesson.", "Create a small Jupyter notebook that reads a public fintech-style dataset.", "Save the notebook to GitHub with a short README describing what you learned."],
    ["Choose one use case: fraud, risk, recommendations, or customer support classification.", "Train and evaluate a simple scikit-learn model; record one metric such as accuracy or precision.", "Publish the code, README, and a screenshot or short write-up in GitHub."],
    ["Wrap your model in a small API or batch pipeline.", "Add logging or monitoring—this is where your AWS and reliability background is a real advantage.", "Document the architecture, trade-offs, and one improvement you would make next."],
    ["Add the project and measurable outcome to your résumé and LinkedIn.", "Tailor two résumé bullets toward ML Engineer, Applied ML Engineer, or AI Platform roles.", "Upload the updated résumé here and run a fresh analysis."],
  ];
  const resources = isAiMl
    ? [[{ label: "Python tutorial", kind: "Read", url: "https://docs.python.org/3/tutorial/" }, { label: "Python full course", kind: "Watch", url: "https://www.youtube.com/watch?v=rfscVS0vtbw" }], [{ label: "scikit-learn getting started", kind: "Read", url: "https://scikit-learn.org/stable/getting_started.html" }, { label: "Machine learning course", kind: "Watch", url: "https://www.youtube.com/watch?v=7eh4d6sabA0" }], [{ label: "FastAPI tutorial", kind: "Build", url: "https://fastapi.tiangolo.com/tutorial/" }, { label: "ML system design guide", kind: "Read", url: "https://developers.google.com/machine-learning/guides/rules-of-ml" }], [{ label: "GitHub project documentation", kind: "Read", url: "https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes" }, { label: "Resume bullet guide", kind: "Read", url: "https://www.indeed.com/career-advice/resumes-cover-letters/resume-bullet-points" }]][index]
    : /\bjavascript\b/i.test(context) ? [{ label: "JavaScript.info Fundamentals", kind: "Read", url: "https://javascript.info/first-steps" }, { label: "JavaScript full course", kind: "Watch", url: "https://www.youtube.com/watch?v=PkZNo7MFNFg" }]
    : /\breact\b/i.test(context) ? [{ label: "React: Quick Start", kind: "Read", url: "https://react.dev/learn" }, { label: "React course", kind: "Watch", url: "https://www.youtube.com/watch?v=bMknfKXIFA8" }]
    : /\btypescript\b/i.test(context) ? [{ label: "TypeScript Handbook", kind: "Read", url: "https://www.typescriptlang.org/docs/handbook/intro.html" }, { label: "TypeScript course", kind: "Watch", url: "https://www.youtube.com/watch?v=30LWjhZzg50" }]
    : /\b(next\.js|nextjs)\b/i.test(context) ? [{ label: "Next.js Learn", kind: "Build", url: "https://nextjs.org/learn" }, { label: "Next.js course", kind: "Watch", url: "https://www.youtube.com/watch?v=wm5gMKuwSYk" }]
    : /\bgraphql\b/i.test(context) ? [{ label: "GraphQL Learn", kind: "Read", url: "https://graphql.org/learn/" }, { label: "GraphQL course", kind: "Watch", url: "https://www.youtube.com/watch?v=ed8SzALpx1Q" }]
    : [{ label: "Write a strong project README", kind: "Read", url: "https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes" }, { label: "STAR interview method", kind: "Practice", url: "https://www.themuse.com/advice/star-interview-method" }];
  const steps = isAiMl ? aiMlSteps[index] : weekSteps[index % weekSteps.length];
  return { steps, resources, outcome: isAiMl ? "Success looks like a visible GitHub project or resume improvement—not just a completed checkbox." : "Success looks like concrete evidence you can show in a resume, portfolio, or interview." };
}
function renderProgress() { const complete = completedWeeks.filter(Boolean).length; const percent = plans.length ? Math.round((complete / plans.length) * 100) : 0; const reopenedIndex = reopenedWeeks.findIndex(Boolean); const nextIndex = reopenedIndex !== -1 ? reopenedIndex : completedWeeks.findIndex(done => !done); const focus = nextIndex === -1 ? "Roadmap complete — re-analyze your updated résumé." : `${plans[nextIndex][0]} ${reopenedIndex !== -1 ? "reopened — ready to review" : "is your current focus"}.`; $("roadmap-progress").innerHTML = `<div><strong>Your progress</strong><p>${focus}</p></div><div class="progress-track" aria-label="${percent}% complete"><i style="width:${percent}%"></i></div><span class="progress-count">${complete}/${plans.length}</span>`; }
function renderRoadmap() { const recommendedIndex = completedWeeks.findIndex(done => !done); renderProgress(); $("roadmap-list").innerHTML = plans.map((p, i) => { const hasEvidence = Boolean(evidenceByWeek[i]); const evidence = reopenedWeeks[i] ? "Reopened — in progress" : hasEvidence ? "Evidence saved — in progress" : completedWeeks[i] ? "Completed — view only" : "One guided task to start"; const action = completedWeeks[i] ? "View completed task →" : "Start guided task →"; const recommended = i === recommendedIndex ? " recommended" : ""; const evidenceClass = hasEvidence && !completedWeeks[i] ? " has-evidence" : ""; const recommendation = i === recommendedIndex ? '<span class="week-recommendation">Recommended first step</span>' : ""; return `<article class="week${completedWeeks[i] ? " done" : ""}${recommended}${evidenceClass}" data-week="${i}"><span class="week-label">${p[0]}</span><div>${recommendation}<h3>${p[1]}</h3><p>${p[2]}</p><span class="week-progress">${evidence}</span><button class="week-action text-button" type="button">${action}</button></div><button class="check" aria-label="Open guided task for ${p[0]}"></button></article>`; }).join(""); document.querySelectorAll(".check,.week-action").forEach(btn => btn.addEventListener("click", () => openWeekTask(Number(btn.closest(".week").dataset.week)))); }
function updateSaveProgressState() { const hasStep = [...document.querySelectorAll(".task-step")].some(step => step.checked); $("save-task-evidence").disabled = Boolean(completedWeeks[activeTaskIndex]) || (!hasStep && !$("task-evidence").value.trim()); }
function openWeekTask(index) { activeTaskIndex = index; const plan = plans[index]; const guidance = guidanceForWeek(index); const savedSteps = taskStepsByWeek[taskKey(index)] || []; const isComplete = completedWeeks[index]; $("task-week").textContent = `${plan[0]} · ${isComplete ? "COMPLETED TASK" : "GUIDED TASK"}`; $("task-title").textContent = plan[1]; $("task-resources").innerHTML = `<p class="eyebrow">START HERE</p>${guidance.resources.map(resource => `<a class="task-resource-link" href="${resource.url}" target="_blank" rel="noopener noreferrer"><span>${resource.kind}</span>${resource.label} <b aria-hidden="true">↗</b></a>`).join("")}`; $("task-evidence").value = evidenceByWeek[index] || ""; $("task-evidence").readOnly = isComplete; $("task-steps").innerHTML = guidance.steps.map((step, stepIndex) => `<li><label><input class="task-step" data-step="${stepIndex}" type="checkbox" ${savedSteps[stepIndex] ? "checked" : ""} ${isComplete ? "disabled" : ""} /> <span>${step}</span></label></li>`).join(""); document.querySelectorAll(".task-step").forEach(step => step.addEventListener("change", updateSaveProgressState)); $("save-task-evidence").hidden = false; $("complete-task").hidden = isComplete; $("reopen-task").hidden = !isComplete; updateSaveProgressState(); $("complete-task").innerHTML = "Mark week complete <span>✓</span>"; setStatus("task-status", isComplete ? "Completed. Reopen task only if you need to edit it." : "", isComplete ? "success" : ""); if (!$("task-dialog").open) $("task-dialog").showModal(); }
function saveTaskState() { if (activeTaskIndex === null) return; evidenceByWeek[activeTaskIndex] = $("task-evidence").value.trim(); taskStepsByWeek[taskKey(activeTaskIndex)] = [...document.querySelectorAll(".task-step")].map(input => input.checked); persistProgress(); renderRoadmap(); }
$("close-task").addEventListener("click", () => $("task-dialog").close());
$("task-evidence").addEventListener("input", updateSaveProgressState);
$("save-task-evidence").addEventListener("click", () => { saveTaskState(); setStatus("task-status", "Task progress saved.", "success"); });
$("complete-task").addEventListener("click", () => { const steps = [...document.querySelectorAll(".task-step")]; if (!steps.length || steps.some(step => !step.checked)) return setStatus("task-status", "Complete all three guided steps before marking this week complete.", "error"); saveTaskState(); completedWeeks[activeTaskIndex] = true; reopenedWeeks[activeTaskIndex] = false; persistProgress(); renderRoadmap(); $("complete-task").innerHTML = "Week completed <span>✓</span>"; const nextMessage = activeTaskIndex < plans.length - 1 ? "Week complete. Choose your next guided task when you are ready." : "Roadmap complete. Update your résumé and re-analyze to measure your progress."; setStatus("task-status", activePlanId ? nextMessage : `${nextMessage} Save this plan to keep your progress.`, "success"); });
$("reopen-task").addEventListener("click", () => { completedWeeks[activeTaskIndex] = false; reopenedWeeks[activeTaskIndex] = true; persistProgress(); renderRoadmap(); openWeekTask(activeTaskIndex); setStatus("task-status", "Task reopened. You can edit it again.", "success"); });
$("reanalyze-task").addEventListener("click", () => { $("task-dialog").close(); document.querySelector('[data-panel="analyze"]').click(); notify("Update your résumé with your new evidence, then choose Reveal my path for an honest new score."); });
renderRoadmap(); $("refresh-roadmap").addEventListener("click", () => { renderRoadmap(); notify("Your current 4-week plan is up to date. Re-analyze after updating your résumé to create a new one."); });
function escapeHtml(value = "") { return String(value).replace(/[&<>'"]/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[char]); }
function renderSavedPlans() {
  const list = $("saved-list");
  if (!activeUser) { list.innerHTML = '<div class="saved-empty">Sign in to see plans you have saved.</div>'; return; }
  if (!savedPlans.length) { list.innerHTML = '<div class="saved-empty">No saved plans yet. Analyze a role, then choose <strong>Save this plan</strong> to keep it here.</div>'; return; }
  list.innerHTML = savedPlans.map((plan, index) => {
    const role = escapeHtml(String(plan.target_role || "").replace(/\s+/g, " ").trim().slice(0, 96));
    const score = plan.analysis?.score ? `${plan.analysis.score}/100` : "Saved plan";
    const done = plan.progress?.completedWeeks?.filter(Boolean).length || 0;
    const date = new Date(plan.created_at).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" });
    const focus = escapeHtml(plan.analysis?.gapTitle || "Open this saved plan to revisit the roadmap.");
    return `<article class="saved-card"><div class="saved-card-top"><div><h3>${role || "Career plan"}</h3><time>${date} · ${done}/4 weeks complete</time></div><span class="saved-score">${score}</span></div><p>${focus}</p><div class="saved-card-actions"><button class="text-button open-saved" data-plan-index="${index}" type="button">Open plan →</button><button class="text-button delete-saved" data-plan-index="${index}" type="button">Delete</button></div></article>`;
  }).join("");
  document.querySelectorAll(".open-saved").forEach(button => button.addEventListener("click", () => {
    const plan = savedPlans[Number(button.dataset.planIndex)]; activePlanId = plan.id; $("job").value = plan.target_role || ""; showResults(plan.analysis || undefined);
    completedWeeks = plans.map((_, index) => Boolean(plan.progress?.completedWeeks?.[index])); evidenceByWeek = plans.map((_, index) => plan.progress?.evidenceByWeek?.[index] || ""); taskStepsByWeek = normalizeTaskSteps(plan.progress?.taskStepsByWeek); reopenedWeeks = plans.map((_, index) => Boolean(plan.progress?.reopenedWeeks?.[index]));
    renderRoadmap(); $("save-plan").textContent = "Update saved plan"; document.querySelector('[data-panel="roadmap"]').click(); notify("Saved plan opened.");
  }));
  document.querySelectorAll(".delete-saved").forEach(button => button.addEventListener("click", async () => {
    const index = Number(button.dataset.planIndex); const plan = savedPlans[index];
    button.disabled = true; button.textContent = "Deleting…";
    const result = await supabaseClient.from("career_plans").delete().eq("id", plan.id).eq("user_id", activeUser.id);
    if (result.error) { button.disabled = false; button.textContent = "Delete"; notify(`Could not delete plan: ${result.error.message}`, true); return; }
    if (activePlanId === plan.id) { activePlanId = null; $("save-plan").textContent = "Save this plan"; }
    savedPlans.splice(index, 1); renderSavedPlans(); notify("Saved plan deleted.");
  }));
}
async function loadSavedPlans() { if (!activeUser || !supabaseClient) return renderSavedPlans(); $("saved-list").innerHTML = '<div class="saved-empty">Loading your saved plans…</div>'; const r = await supabaseClient.from("career_plans").select("id, target_role, analysis, roadmap, progress, created_at").eq("user_id", activeUser.id).order("created_at", { ascending: false }); if (r.error) { $("saved-list").innerHTML = `<div class="saved-empty">Could not load saved plans: ${escapeHtml(r.error.message)}</div>`; return; } const byRole = new Map(); (r.data || []).forEach(plan => { const key = String(plan.target_role || "").trim().toLowerCase(); const current = byRole.get(key); const done = plan.progress?.completedWeeks?.filter(Boolean).length || 0; const currentDone = current?.progress?.completedWeeks?.filter(Boolean).length || 0; if (!current || done > currentDone) byRole.set(key, plan); }); savedPlans = [...byRole.values()]; renderSavedPlans(); }
$("refresh-saved").addEventListener("click", loadSavedPlans);
function downloadPlan() { const text = [`PATHWISE — AI CAREER COPILOT`, "", `Target role`, $("job").value, "", `Fit score: ${$("score").textContent}/100`, `ATS keyword coverage: ${$("ats-score").textContent}`, "", "YOUR EDGE", $("edge-title").textContent, $("edge-copy").textContent, "", "FOCUS NEXT", $("gap-title").textContent, $("gap-copy").textContent, "", "4-WEEK ROADMAP", ...plans.flatMap(([week, title, detail], index) => [`${completedWeeks[index] ? "✓ Completed" : "○ To do"} — ${week}: ${title}`, detail, ""])].join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([text], { type: "text/plain" })); link.download = "pathwise-career-plan.txt"; link.click(); URL.revokeObjectURL(link.href); notify("Career plan downloaded."); }
$("download-plan").addEventListener("click", downloadPlan);
$("improve-score").addEventListener("click", () => { document.querySelector('[data-panel="roadmap"]').click(); setTimeout(() => document.querySelector(".week.recommended")?.scrollIntoView({ behavior: "smooth", block: "center" }), 250); });
$("improve-resume").addEventListener("click", () => { $("resume-suggestions").hidden = true; setStatus("resume-status"); if (!$("resume-dialog").open) $("resume-dialog").showModal(); });
$("close-resume-dialog").addEventListener("click", () => $("resume-dialog").close());
$("generate-resume").addEventListener("click", async () => { const resume = $("resume").value.trim(); const job = $("job").value.trim(); if (!resume || !job) return setStatus("resume-status", "Add your résumé and target role before generating suggestions.", "error"); const button = $("generate-resume"); button.disabled = true; button.textContent = "Generating…"; setStatus("resume-status"); try { const response = await fetch("/api/improve-resume", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ resume, job }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); $("resume-summary").textContent = data.summary; $("resume-bullets").innerHTML = data.bullets.map(bullet => `<li>${escapeHtml(bullet)}</li>`).join(""); chips("resume-keywords", data.keywords); $("resume-note").textContent = data.note; $("resume-suggestions").hidden = false; setStatus("resume-status", "Suggestions ready. Review and adapt them before using them.", "success"); } catch (error) { setStatus("resume-status", error.message || "Could not generate suggestions yet.", "error"); } finally { button.disabled = false; button.innerHTML = "Generate suggestions <span>→</span>"; } });
$("copy-resume-summary").addEventListener("click", async () => { try { await navigator.clipboard.writeText($("resume-summary").textContent); setStatus("resume-status", "Summary copied.", "success"); } catch { setStatus("resume-status", "Select and copy the summary manually.", "error"); } });
$("copy-resume-suggestions").addEventListener("click", async () => { const text = [`TAILORED SUMMARY`, $("resume-summary").textContent, "", "BULLET IDEAS TO REVIEW", ...[...$("resume-bullets").querySelectorAll("li")].map(item => `• ${item.textContent}`), "", "RELEVANT KEYWORDS", [...$("resume-keywords").querySelectorAll("span")].map(item => item.textContent).join(", ")].join("\n"); try { await navigator.clipboard.writeText(text); setStatus("resume-status", "Suggestions copied.", "success"); } catch { setStatus("resume-status", "Select and copy the suggestions manually.", "error"); } });
async function findExistingPlan(targetRole) { const r = await supabaseClient.from("career_plans").select("id, progress").eq("user_id", activeUser.id).eq("target_role", targetRole); if (r.error) return r; const plansForRole = r.data || []; plansForRole.sort((a, b) => (b.progress?.completedWeeks?.filter(Boolean).length || 0) - (a.progress?.completedWeeks?.filter(Boolean).length || 0)); return { data: plansForRole[0] || null, error: null }; }
$("save-plan").addEventListener("click", async () => { if (!activeUser) return openAuth(); if (!lastAnalysis) return notify("Analyze your résumé and target role before saving a plan.", true); if (!$("job").value.trim()) return notify("Add a target role before saving this plan.", true); const button = $("save-plan"); const payload = { user_id: activeUser.id, target_role: $("job").value, analysis: lastAnalysis, roadmap: plans.map(([week, title, detail]) => ({ week, title, detail })), progress: { completedWeeks, evidenceByWeek, taskStepsByWeek, reopenedWeeks } }; button.disabled = true; button.textContent = "Saving…"; let r; if (activePlanId) r = await supabaseClient.from("career_plans").update(payload).eq("id", activePlanId).select("id, target_role, analysis, roadmap, progress, created_at").single(); else { const existing = await findExistingPlan(payload.target_role); if (existing.error) r = existing; else if (existing.data) { if (!completedWeeks.some(Boolean) && existing.data.progress?.completedWeeks) { completedWeeks = plans.map((_, index) => Boolean(existing.data.progress.completedWeeks[index])); evidenceByWeek = plans.map((_, index) => existing.data.progress.evidenceByWeek?.[index] || ""); taskStepsByWeek = normalizeTaskSteps(existing.data.progress.taskStepsByWeek); reopenedWeeks = plans.map((_, index) => Boolean(existing.data.progress.reopenedWeeks?.[index])); payload.progress = { completedWeeks, evidenceByWeek, taskStepsByWeek, reopenedWeeks }; } r = await supabaseClient.from("career_plans").update(payload).eq("id", existing.data.id).select("id, target_role, analysis, roadmap, progress, created_at").single(); } else r = await supabaseClient.from("career_plans").insert(payload).select("id, target_role, analysis, roadmap, progress, created_at").single(); } button.disabled = false; if (!r.error) { activePlanId = r.data.id; button.textContent = "Update saved plan"; } else button.textContent = activePlanId ? "Update saved plan" : "Save this plan"; notify(r.error ? r.error.message : "Plan and progress saved to your Pathwise account.", Boolean(r.error)); if (!r.error) loadSavedPlans(); });
$("answer").addEventListener("input", e => { $("word-count").textContent = `${e.target.value.trim() ? e.target.value.trim().split(/\s+/).length : 0} words`; });
const questions = ["Tell me about a time you made a difficult technical trade-off.", "How would you make an analytics dashboard more accessible?", "Describe a project where you influenced a decision without formal authority."];
let questionIndex = 0;
$("new-question").addEventListener("click", () => { questionIndex = (questionIndex + 1) % questions.length; $("question").textContent = questions[questionIndex]; $("answer").value = ""; $("word-count").textContent = "0 words"; $("feedback").hidden = true; });
$("score-answer").addEventListener("click", async () => { const answer = $("answer").value.trim(); const job = $("job").value.trim(); const feedback = $("feedback"); if (!answer) { feedback.hidden = false; feedback.innerHTML = "<strong>Start with one concrete example.</strong> Add a situation, the decision you made, and what changed as a result."; return; } if (!job) { feedback.hidden = false; feedback.innerHTML = "<strong>Add a target role first.</strong> Pathwise needs the role to give relevant interview feedback."; return; } if (demoMode) { feedback.hidden = false; feedback.innerHTML = "<strong>Clear structure—now make the impact measurable.</strong> Your answer should name the trade-off, explain why it mattered to users, and finish with a concrete result such as time saved, adoption, or performance improved."; return; } try { const response = await fetch("/api/interview", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ answer, job }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); feedback.hidden = false; feedback.innerHTML = `<strong>${data.headline}</strong> ${data.feedback}`; } catch (error) { feedback.hidden = false; feedback.innerHTML = `<strong>Could not score yet.</strong> ${error.message}`; } });
let introKind = "recruiter";
document.querySelectorAll(".intro-option").forEach(button => button.addEventListener("click", () => { introKind = button.dataset.introKind; document.querySelectorAll(".intro-option").forEach(option => option.classList.toggle("active", option === button)); }));
$("generate-intro").addEventListener("click", async () => { const resume = $("resume").value.trim(); const job = $("job").value.trim(); if (!resume) return notify("Add your résumé or experience before crafting an introduction.", true); if (!job) return notify("Add a target role before crafting an introduction.", true); const button = $("generate-intro"); button.disabled = true; button.textContent = "Crafting…"; try { const response = await fetch("/api/introduction", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ resume, job, kind: introKind }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); $("intro-script").textContent = data.introduction; $("intro-tips").innerHTML = data.tips.map(tip => `<li>${escapeHtml(tip)}</li>`).join(""); $("intro-output").hidden = false; } catch (error) { notify(`Could not craft your introduction yet: ${error.message || "Please try again."}`, true); } finally { button.disabled = false; button.innerHTML = "Craft my introduction <span>→</span>"; } });
$("copy-intro").addEventListener("click", async () => { const text = $("intro-script").textContent; if (!text) return; try { await navigator.clipboard.writeText(text); notify("Introduction copied."); } catch { notify("Select and copy the introduction manually.", true); } });
$("results").classList.add("empty");
initAuth();
